# 理解生成器

Generator函数

```javascript
function* gen() {
    console.log("1");
    yield 123
    console.log("3");
    return 234
}
const hw = gen();
// undefined
hw.next()
1
// 返回值 {value: 123, done: false}
console.log(hw.next())
3
// 返回值 {value: 234, done: true}
```

**hw**不会执行函数执行函数的。只有触发了**hw**的**next**函数，才会开始执行函数，到下一个**yield**这个值的返回值。

注意：直接使用`gen.next()`会报出语法错误，指出gen.next不是一个函数。



### 用法推荐

```javascript
// 遍历
var arr = [1, [[2, 3], 4], [5, 6]];

var flat = function* (a) {
  var length = a.length;
  for (var i = 0; i < length; i++) {
    var item = a[i];
    if (typeof item !== 'number') {
      yield* flat(item);
    } else {
      yield item;
    }
  }
};
// for ... of ...可以相当于next函数的作用
for (var f of flat(arr)) {
  console.log(f);
}
1, 2, 3, 4, 5, 6
```

```javascript
// yield表达式在另外一个表达式中，必须放在圆括号中
function* demo() {
  console.log('Hello' + (yield)); // OK
  console.log('Hello' + (yield 123)); // OK
}
var b = demo()
b.next()
// 返回值 {value: undefined, done: false}
b.next()
// yield本身的返回值undefined，或者说总是返回undefined
Helloundefined
// 返回值 {value: 123, done: false}
b.next()
Helloundefined
// 返回值 {value: undefined, done: true}
```

```javascript
// 把Generator赋值给对象的Symbol.iterator属性，从而使该对象具有Iterator接口
var myIterable = {};
myIterable[Symbol.iterator] = function* () {
    yield 1;
    yield 2;
    yield 3;
};
[...myIterable]
(3) [1, 2, 3]
```

````javascript
// next方法可以带一个参数，该参数就会被当做上一个yield表达式的返回值
// 语法意义是通过next方法可以向函数体内部注入值，可以从外面调整函数的行为。
function* f() {
    for(var i = 0; true; i++) {
        var reset = yield i;
        if(reset) {
            i = -1;
        }
    }
}
var g = f();
g.next()
// 返回值 {value: 0, done: false}
g.next()
// 返回值 {value: 1, done: false}
g.next()
// 返回值 {value: 2, done: false}
g.next(true)
// 返回值  {value: 0, done: false}
````

```javascript
// Generator的throw方法
var g = function* () {
  try {
    yield;
  } catch (e) {
    console.log('内部捕获', e);
  }
};

var i = g();
// throw方法抛出的错误要被内部捕获，前提是必须至少执行过一次next方法。因为执行第一次执行next方法相当于启动执行Generator函数。
i.next();
// 返回值 {value: undefined, done: false}
try {
  i.throw('a');
  i.throw('b');
} catch (e) {
  console.log('外部捕获', e);
}
// 内部捕获是因为 这个generator还没有执行完毕，所以throw就把错误抛到g中。
内部捕获 a
外部捕获 b


// 相反的例子
var g = function* () {
  try {
    yield;
  } catch (e) {
    console.log('内部捕获', e);
  }
};

var i = g();
undefined
i.next()
{value: undefined, done: false}
i.next()
{value: undefined, done: true}
try {
  i.throw('a'); 
  i.throw('b');
} catch (e) {
  console.log('外部捕获', e);
}
外部捕获 a
```

```javascript
// Generator 函数返回的遍历器对象，还有一个return方法，可以返回给定的值，并且终结遍历 Generator 函数。
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

var g = gen();
// 也可以直接使用gen().next()方法，不用重新定义函数
undefined
g.next()
// 返回值 {value: 1, done: false}
g.return('foo')
// 返回值 {value: "foo", done: true}
// 如果return方法调用时，不提供参数，则返回值的value属性为undefined。
g.next("2345")
// 返回值 {value: undefined, done: true}

```

```javascript
// 如果 Generator 函数内部有try...finally代码块，那么return方法会推迟到finally代码块执行完再执行。
function* numbers () {
  yield 1;
  try {
    yield 2;
    yield 3;
  } finally {
    yield 4;
    yield 5;
  }
  yield 6;
}
var g = numbers();
g.next() 
// 返回值 { value: 1, done: false }
g.next() 
// 返回值 { value: 2, done: false }
// 调用return方法后，就会直接进入到finally的方法中
g.return(7) 
// 返回值 { value: 4, done: false }
g.next() 
// 返回值 { value: 5, done: false }
g.next() 
// 返回值 { value: 7, done: true }
```



